# 直接从镜像启动容器
version: "3.9"
services:
  openai-router:
    image: docker.1ms.run/506610466/openai-router:0.1.14
    container_name: openai-router
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data:/app/data
    ports:
      - "8082:8082"
    restart: unless-stopped
    command: openai-router --host 0.0.0.0 --port 8082
  
